### PR TITLE
Added a basic Patient Record elasticsearch controller

### PR DESCRIPTION
**Pull request by modelarious**
Added a basic Patient Record elasticsearch controller

### CODE REVIEW

**Comment by tnguyen10** [comment]
What's the difference between patient's record and record?

**Comment by modelarious** [comment]
@tnguyen10 Patient Record stores arrays of photos, locations, body location photo.  Record is just the Comment, Title and UserID.  So there's more info to store for a patient record (even if it's just the ids of associated pictures or locations, etc)

**Comment by modelarious** [comment]
I could be wrong, but I think the way mappings work for elastic search prevents us from putting them in the same "type"

**Comment by tnguyen10** [comment]
ok, I'll merge them now but we should make sure that they share the same record id if they are the same record

**Pull request merged**
