### PR TITLE
Makes everything works with elastic search database

### PR DESCRIPTION
**Pull request by tnguyen10**
DeletePatientsTask() implemented
add parameters.size to increase size of elastic search results

- Please run to see if there's any bug

### CODE REVIEW

**Comment by deasisrj1** [comment]
It signs up successfully but when a log in attempt is made user is not found

**Comment by deasisrj1** [comment]
When logged in as a patient, after creating a problem and adding a record to the problem, modifying problem and saving it makes the app crash

**Comment by tnguyen10** [comment]
Yeah I'm testing it right now after the merged, it crashed for me too.
Before the merge it was working for add problem and add record.

**Comment by tnguyen10** [comment]
Probably dues to the switch to online database, I'll try to fix it asap. Could you guys also look over it too and see if there's anything wrong

**Comment by tnguyen10** [comment]
Just wondering how are you guys getting the problem/ record to be modified?

**Comment by deasisrj1** [comment]
it might be from the ModifyProblemController on saveProblem function it looks like its deleting the old problem and add a new problem instead of editing the actual object itself

**Comment by tnguyen10** [comment]
Modify problem and modify records should work (on my device, so please run and check).
Since this is a temporary fix, the code looks terrible, will refactor later

**Pull request merged**
