### PR TITLE
Annotated the tests with pass fail status

### PR DESCRIPTION
**Pull request by modelarious**

### CODE REVIEW

**Comment by modelarious** [comment]
Can whoever reviews this run the tests and verify they get the same status as me?

**Comment by tnguyen10** [comment]
the controllers pass, fails are the same for me

for the ui test
PatientHomeMenuActivityTest: onLogoutClickLogsUserOut() fails (the very finicky one)
SignUpInstrumentedTest: NoConnectionException fails for me (I'm not sure how to turn off data, so I turned off my laptop's wifi, so not sure it this is one is valid or not)

**Comment by modelarious** [comment]
Perfect, good to know.  If you swipe down from the top bar on the phone, there's usually a bar at the top that appears that lets you control if Wifi is on and if data is on.

**Comment by modelarious** [comment]
Hey @tnguyen10 could you "Approve" these changes using "Review Changes" under the "Files Changed" tab at the top of this pull request?

**Pull request merged**
