### PR TITLE
Implemented query for patients, should make login work if UserID is passed in

### PR DESCRIPTION
**Pull request by modelarious**
Implemented query for patients, should make login work if UserID is passed in

Controller tests are being weird.  The controller works fine when used in the app (with modifications to Login activity that I can't include here due to merge conflicts with other requests).  It is able to add patients for sign up and fetch patients to log the user in.  But all the tests immediately result in a null pointer exception.  The tests themselves are written correctly as far as I can tell.  Does it need to exist within an activity (so an instrumented test?).  Does it need to be non static?

### CODE REVIEW

**Comment by modelarious** [comment]
Please tag me if this is going to change the login activity at all!

**Comment by tnguyen10** [comment]
Not sure if you fixed this yet but I think the null pointer exception comes from the patients list not being initialize

My guess is that new ElasticsearchPatientController.GetPatientTask().execute().get(); probably didn't get executed properly because it's in the doInBackground method. 

doInBackground is probably invoked whenever the app is actually launch and since I don't think ElasticSearchPatientControllerTest launch the app, it's probably never been called.

**Comment by modelarious** [comment]
You're probably right.  To test this we may need to initialize an activity and run the controller within some context then.  Maybe a mock activity that has a button for each of the actions the controller can take with a text box to pass in parameters.  I'll give this a try (will post results on #19).  Will also add these comments to that issue.

**Comment by modelarious** [comment]
Unless there is another way to test async tasks, I'll also look into that.  Either way, that will be handled and tracked by #19. @tnguyen10

**Pull request merged**
