### PR TITLE
OfflinePatientController, OfflineProblemController

### PR DESCRIPTION
**Pull request by tnguyen10**
[issue #214](https://github.com/CMPUT301F18T20/MedicalPhotoRecord/issues/214) tracking

### CODE REVIEW

**Comment by tnguyen10** [comment]
addDeleteProblemController
browseProblemsController
browseProblemActivity
addProblemActivity

-done-

**Comment by tnguyen10** [comment]
All refactoring for problems (browse, add, modify, delete, view) should be done, modify user is also done. Re-wrote controllers test for those. Wrote test for offline patient and problem controllers. 

I also changed the name of the controller and activity (so that it's consistent). If any of you guys' controllers uses them they'll be changed too.

**Comment by modelarious** [comment]
Current state of these tests for me:
```
AddDeleteProblemControllerTest:
    both fail

BrowseUserControllerTest:
    fails

BrowseUserProblemControllerTest:
    fails

Elasticsearch:
    Patient:
        all pass

    PatientRecord:
        all pass except modifyPatientRecordSavesDateChangesBUGTest

    Record:
        all pass except modifyRecordSavesDateChangesBUGTest

    Problem:
        all pass except modifyProblemSavesDateChangesBUGTest

    Provider:
        all pass

ModifyPatientRecordControllerTest:
    Crashes on testSaveUser

OfflinePatientControllerTest:
    all pass

OfflineProblemControllerTest:
    all pass

SignUpControllerTest:
    all pass

**Comment by tnguyen10** [comment]
`BrowseUserControllerTest:
    fails

Elasticsearch:
    Patient:
        all pass

    PatientRecord:
        all pass except modifyPatientRecordSavesDateChangesBUGTest

    Record:
        all pass except modifyRecordSavesDateChangesBUGTest

    Problem:
        all pass except modifyProblemSavesDateChangesBUGTest

    Provider:
        all pass
`

All others should pass. Could you re-run the test again? on tnguyenRefactor branch

**Comment by tnguyen10** [comment]
All these fails for me
1. Controllers.BrowseeUserControllerTest
2. Controllers.ElasticsearchPatientRecordControllerTest (modifyPatientRecordSavesDateChangesBUG)
3. Controllers.ElasticsearchProblemControllerTest (modifyProblemSavesDateChangesBUG)
4. Controllers.ElasticsearchRecordControllerTest (modifyRecordSavesDateChangesBUG, getRecordByProblemUUIDTest)

All others pass, could you re run the test again? on tnguyenRefactor branch

**Comment by modelarious** [comment]
Not sure what the issue was the first time, but now all that fails for me is

Controllers.BrowseUserControllerTest
Controllers.ElasticsearchPatientRecordControllerTest (modifyPatientRecordSavesDateChangesBUG)
Controllers.ElasticsearchProblemControllerTest (modifyProblemSavesDateChangesBUG)
Controllers.ElasticsearchRecordControllerTest (modifyRecordSavesDateChangesBUG)

**Pull request merged**
